services:
    redis:
        image: redis:latest
        container_name: weather-monitoring-hourly
        ports:
            - "6379:6379"
    rabbitmq:
        image: rabbitmq
        container_name: coelho
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
            - rabbitmq_log:/var/log/rabbitmq
    mongo:
        image: mongo
        restart: always
        container_name: weather-monitoring-daily
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: dev
            MONGO_INITDB_ROOT_PASSWORD: dev

volumes:
    rabbitmq_data:
    rabbitmq_log:
