services:
    redis:
        image: redis:latest
        container_name: redis-daily-storage
        ports:
            - "6379:6379"
    rabbitmq:
        image: rabbitmq
        container_name: coelho
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
            - rabbitmq_log:/var/log/rabbitmq

volumes:
    rabbitmq_data:
    rabbitmq_log:
